class Car
{
    String model;
    int price;
    // public String toString(){
    //     return model +" : " + price;
    // }
    
    // public boolean equals(Car that){
    //         return this.model.equals(that.model) && this.price == that.price;
    // }
    // generated by IDE
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((model == null) ? 0 : model.hashCode());
        result = prime * result + price;
        return result;
    }
    @Override
    public String toString() {
        return "Car [model=" + model + ", price=" + price + "]";
    }
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        Car other = (Car) obj;
        if (model == null) {
            if (other.model != null)
                return false;
        } else if (!model.equals(other.model))
            return false;
        if (price != other.price)
            return false;
        return true;
    }
    
}
public class Equals {
    public static void main(String[] args) {
        Car obj = new Car();
        obj.model="BMW";
        obj.price=3400;
        Car obj2 = new Car();
        obj2.model="BMW";
        obj2.price=3400;
        
        // boolean result = obj.equals(obj2);
        System.out.println(obj.equals(obj2));
        System.out.println(obj2);
    }
}
